---
title: "R Notebook"
output: html_notebook
---



```{r}
library(epigraphdb)
library(tidyverse)
source("../helper_functions.R")
source("functions_literature.R")
```

This is a raw cypher query to  extract a literature space
```{}
MATCH (gwas:Gwas)-[gs1:GWAS_TO_LITERATURE_TRIPLE]->(s1:LiteratureTriple) -[:SEMMEDDB_OBJ]->(st:LiteratureTerm)
WHERE gwas.id = '...'
AND gs1.pval < 0.01
MATCH (s1)-[:SEMMEDDB_SUB]-(st1:LiteratureTerm) 
MATCH (gwas)-[:GWAS_TO_LITERATURE]-(lit:Literature)-[]-(s1)
RETURN lit.id, lit.year,  gwas {.id, .trait}, 
gs1 {.pval, .localCount}, st1 {.name, .type}, s1 {.id, .subject_id, .object_id, .predicate}, st {.name, .type}
```

```{r}    
# extract literature space R function

extract_literature_space <- function(id){
  
  ## this query is too heavy for R when literature space is huge (like for BC)
  
 # query =  paste0("
 #     MATCH (gwas:Gwas)-[gs1:GWAS_TO_LITERATURE_TRIPLE]->(s1:LiteratureTriple) -[:SEMMEDDB_OBJ]->(st:LiteratureTerm)
 #     WHERE gwas.id = '", id, "'
 #     AND gs1.pval < 0.01
 #     MATCH (s1)-[:SEMMEDDB_SUB]-(st1:LiteratureTerm) 
 #     MATCH (gwas)-[:GWAS_TO_LITERATURE]-(lit:Literature)-[]-(s1)
 #     RETURN lit.id, lit.year,  gwas {.id, .trait}, 
 #     gs1 {.pval, .localCount}, st1 {.name, .type}, s1 {.id, .subject_id, .object_id, .predicate}, st {.name, .type}
 #     ")
 # out<-query_epigraphdb_as_table(query)
 # dim(out)

  
  # so we're going to split it in two parts (tested that this approach delivers the same result)
  
  # 1: extract GWAS triples and their terms
  query1 =  paste0("
      MATCH (gwas:Gwas)-[gs1:GWAS_TO_LITERATURE_TRIPLE]->(s1:LiteratureTriple) -[:SEMMEDDB_OBJ]->(st:LiteratureTerm)
      WHERE gwas.id = '", id, "'
      AND gs1.pval < 0.01
      MATCH (s1)-[:SEMMEDDB_SUB]-(st1:LiteratureTerm) 
      RETURN  gwas {.id, .trait}, 
      gs1 {.pval, .localCount}, st1 {.name, .type}, s1 {.id, .subject_id, .object_id, .predicate}, st {.name, .type}
      ")
  # gwas and triples  
  out1<-query_epigraphdb_as_table(query1)
  
  if (dim(out1)[1]==0 ){
    print(paste0("======= ", id, " : empty literature space"))
    return(data.frame())
    
  } else {
    
    dim(out1) # 24239
    triple_id_list <- unique(out1$s1.id) #23278
    length(triple_id_list)
    
    
    # 2: for these triples, extract literature nodes
    query2 =  paste0("
        MATCH (s1:LiteratureTriple)-[]-(lit:Literature)
        WHERE s1.id in ['", paste0(triple_id_list, collapse = "', '"),"'] 
        MATCH (lit)-[:GWAS_TO_LITERATURE]-(gwas:Gwas)
        WHERE gwas.id = '", id, "'
        RETURN gwas.id, lit.id, lit.year, s1 {.id, .subject_id, .object_id, .predicate}
        ")
      
    out2<-query_epigraphdb_as_table(query2) 
    dim(out2)
    
    triple_id_list2 <- unique(out2$s1.id) #23142
    length(triple_id_list2)
    
    litspace <- full_join(out1, out2, 
                              by = c("s1.subject_id"="s1.subject_id",
                                    "s1.predicate"="s1.predicate",
                                    "s1.id" = "s1.id" ,
                                    'gwas.id' = 'gwas.id',
                                    "s1.object_id" ="s1.object_id" )) %>% 
        filter(!is.na(lit.id))
    
   trait <- unique(litspace$gwas.trait)
    
   print(paste0("Lit space of ", trait, " - ", id, ": ", dim(litspace)[1] ))  
   dim(litspace)
   
   litspace<- litspace %>% rowwise() %>% 
      mutate(st1.type = paste0(unlist(st1.type), collapse="/")) %>%  
      mutate(st.type = paste0(unlist(st.type), collapse="/"))
   return(litspace)
  }

}
```


```{r}
### Apply to breast cancer 

id = 'ieu-a-1126' 
space1<-extract_literature_space(id)
dim(space1) #77496 (63907 w/o gwas cols?)

id = 'finn-a-C3_BREAST' 
space2<-extract_literature_space(id)
dim(space2) #56878 (47473)


bc_space <- bind_rows(space1, space2) %>% select(-gwas.id, -gwas.trait, -gs1.localCount, -gs1.pval) %>% distinct()
dim(bc_space) #65738


bc_space %>%  write_csv("literature_outputs/breast_cancer_litspace_prod.csv")
```


```{r}
# read list of traits for follow up
trait_df_all <- read_tsv("../01_MR_related/mr_evidence_outputs/trait_for_followup.tsv") %>% 
            select(id, trait, exposure_cat) %>% distinct()

# traits with the same name or trait that ar eunlike to match to something meaningful
ignore_traits<- c('ieu-a-95', 'ieu-a-974', 'ukb-a-248', 'ukb-b-4650', 'ukb-a-34', 'ukb-a-35', 'ukb-d-30760_irnt', 'ukb-b-16881','ukb-a-316', 'ukb-a-317',
                  'ieu-a-299', 	'ukb-a-388', 'ieu-a-101','ieu-a-51', 'prot-a-2396', 'prot-a-1541','ieu-a-62', 	'ukb-b-9405', 'ieu-a-105', 'ieu-a-109', 'ieu-a-783')

trait_df_all<- trait_df_all %>% 
   mutate(lit_analysis = case_when(
             id %in% ignore_traits ~ F,
             grepl("^X-", trait) ~ F,
             grepl("HDL|VLDL|LDL", trait) ~ F, ## ignoring all lipids at this time (may need to extract for them separately)
             TRUE ~ T) )

write_tsv(trait_df_all, "traits_marked_for_lit_analysis.tsv")


# select we want to keep
trait_df <- trait_df_all %>%  filter(lit_analysis == T)

lit_spaces<-list()
id_list <- trait_df$id
length(id_list) # 238

for ( id in id_list){
  lit_spaces[[id]] <-extract_literature_space(id)
}
save(lit_spaces, file="literature_outputs/lit_spaces_finalset.RData")


```


```{r}
# identify traits with empty lit spaces
zero_lit <- c()

for (i in 1:length(lit_spaces)){
  if (dim(lit_spaces[[i]])[1] == 0){
    zero_lit <- c(zero_lit, names(lit_spaces)[i])
  }
}
trait_df %>% filter(id %in% zero_lit) %>% View()

# save dim of spaces to trait_df_all table
for (i in 1:length(trait_df_all$id)){
  id <- trait_df_all$id[i]
  
  if (id %in% names(lit_spaces)){
    trait_df_all$lit_space_size[i]<-dim(lit_spaces[[id]])[1]
  }else{
    trait_df_all$lit_space_size[i]<-NA
  }
}
write_tsv(trait_df_all, "literature_outputs/traits_marked_for_lit_analysis.tsv")

```



```{r}
#load("literature_outputs/lit_spaces_finalset.RData")

## testing tidying function

dat<-lit_spaces[["met-a-652"]] 
dim(dat)
datout<- tidy_lit_space(dat)

datout %>% select(term1, predicate, term2) %>% distinct() %>% dim() # unique triples
datout %>% select(term1, term2) %>% distinct() %>% dim() # unique pairs

```


```{r}
## tidtying lit sapces for loop

tidy_litspace <- list()

for (i in 1:length(lit_spaces)){
  if (dim(lit_spaces[[i]])[1] > 0){
    print(paste("tidying... " , i, names(lit_spaces)[i] ))
    
    tidy_litspace[[names(lit_spaces)[i]]] <- tidy_lit_space(lit_spaces[[i]])
  }
}

```

```{r}
# read prev version
trait_df_all <- read_tsv("literature_outputs/traits_marked_for_lit_analysis.tsv") %>% select(1:5)

# save dim to table
for (i in 1:length(trait_df_all$id)){
  id <- trait_df_all$id[i]
  
  if (id %in% names(tidy_litspace)){
    
    trait_df_all$lit_space_size_tidy[i] <- dim(tidy_litspace[[id]])[1]
    
    trait_df_all$unique_triples[i] <- dim(tidy_litspace[[id]] %>% select(term1, predicate, term2) %>% distinct() )[1]
    
    trait_df_all$unique_pairs[i] <- dim(tidy_litspace[[id]] %>% select(term1, term2) %>% distinct() )[1]

  }else{
    trait_df_all$lit_space_size_tidy[i]<-NA
    trait_df_all$unique_triples[i]<-NA
    trait_df_all$unique_pairs[i]<-NA
  }
}

write_tsv(trait_df_all %>%  mutate(across(everything(), ~replace_na(.x, 0))),
          "literature_outputs/traits_marked_for_lit_analysis.tsv")
```

```{r}
# count available lit space by categories
counts_by_cat <- list(
  queried=trait_df_all %>% filter(lit_analysis ==1 ) %>% count(exposure_cat) %>% rename(queried=n) %>% column_to_rownames('exposure_cat') %>% t() %>% as_data_frame(),
  total=trait_df_all %>% filter(lit_space_size_tidy > 0) %>% count(exposure_cat) %>% rename(total=n) %>% column_to_rownames('exposure_cat') %>% t() %>% as_data_frame(),
  `<=5`=trait_df_all %>% filter(lit_space_size_tidy > 0 & lit_space_size_tidy <=5) %>% count(exposure_cat) %>% rename(`<=5`=n) %>% column_to_rownames('exposure_cat') %>% t() %>% as_data_frame(),
  `<=50`=trait_df_all %>% filter(lit_space_size_tidy > 5 & lit_space_size_tidy <=50) %>% count(exposure_cat) %>% rename(`<=50`=n) %>% column_to_rownames('exposure_cat') %>% t() %>% as_data_frame(),
  `>50`=trait_df_all %>% filter(lit_space_size_tidy > 50) %>% count(exposure_cat) %>% rename(`>50`=n) %>% column_to_rownames('exposure_cat') %>% t() %>% as_data_frame())

counts_by_cat_df <- bind_rows(counts_by_cat) %>% t() %>% as.data.frame() %>% rownames_to_column('exposure_cat') %>% mutate(across(everything(), ~replace_na(.x, 0))) 

colnames(counts_by_cat_df)[2:6] <- names(counts_by_cat)
write_tsv(counts_by_cat_df, "literature_outputs/available_litspace_counts_by_exposure_cat.tsv")
```

```{r}
tidy_litspace[["ukb-a-269"]] %>% View()


tidy_litspace[["prot-a-1148"]] %>% filter(term2.type=='dsyn') %>% count(term2, sort=T)

# any version of the key term
tidy_litspace[["prot-a-1148"]] %>% filter(grepl("ferritin", term1, ignore.case = T) | grepl("ferritin", term2, ignore.case = T)) 


#for each trait name, nee dto get its al names, ot name core part
tidy_litspace[["prot-a-1117"]] %>% filter(grepl("filamin|flna", term1, ignore.case = T) | grepl("filamin|flna", term2, ignore.case = T) ) %>% View()

FLNA
```




```{r}
# combining lit space of related traits

#load("literature_outputs/lit_spaces_finalset.RData")
#view(lit_spaces)

combine_lit_spaces <- function(lit_spaces, names){
  lit_spaces_subset <- lit_spaces[names]
  space <- bind_rows(lit_spaces_subset) %>% 
    select(-gwas.id, -gwas.trait, -gs1.localCount, -gs1.pval) 
  return(space)
}


related_traits <- list(
  height = c('ieu-a-1034','ukb-a-195', 'ukb-b-10787'),
  bmi = c('ieu-a-107',	'ukb-b-19953'),
  obesity = c(	'ieu-a-93',	'ieu-a-91',	'ieu-a-90',	'ieu-a-85'),
  waist_hip = c('ieu-a-68','ieu-a-75','ieu-a-99'),
  fruit = c('ukb-b-3881','ukb-b-16576','ukb-b-2221'),
  menopause = c('ukb-b-18105' , 'ukb-b-17422'),
  hrt = c('ukb-b-9487', 'ukb-b-18541'),
  birth = c('ukb-a-320', 'ukb-b-1209')
)


combined_lit_spaces <- list()
for (i in names(related_traits)) {
  combined_lit_spaces[[i]] <- combine_lit_spaces(lit_spaces, related_traits[[i]])
}

save(combined_lit_spaces, file="literature_outputs/lit_spaces_combined_traits.RData")
```



```{r}
## tidying lit sapces for loop
#load("literature_outputs/lit_spaces_combined_traits.RData")
View(combined_lit_spaces)

tidy_combined_litspace <- list()

for (i in 1:length(combined_lit_spaces)){
  if (dim(combined_lit_spaces[[i]])[1] > 0){
    print(paste("tidying... " , i, names(combined_lit_spaces)[i] ))
    
    tidy_combined_litspace[[names(combined_lit_spaces)[i]]] <- tidy_lit_space(combined_lit_spaces[[i]])
  }
}
save(tidy_combined_litspace, file="literature_outputs/lit_spaces_combined_traits_tidy.RData")

```

```{r}
# calculate lit spce / triples/ pair for combined spaces

#load("literature_outputs/lit_spaces_combined_traits_tidy.RData")

trait_df_comb <- data_frame(trait= names(tidy_combined_litspace))

for (i in 1:length(trait_df_comb$trait)){
  
  trait_comb_name <- trait_df_comb$trait[i]

  trait_df_comb$lit_space_size_tidy[i] <- dim(combined_lit_spaces[[trait_comb_name]])[1]
  
  trait_df_comb$unique_triples[i] <- dim(tidy_combined_litspace[[trait_comb_name]] %>% select(term1, predicate, term2) %>% distinct() )[1]
  
  trait_df_comb$unique_pairs[i] <- dim(tidy_combined_litspace[[trait_comb_name]] %>% select(term1, term2) %>% distinct() )[1]

}

write_tsv(trait_df_comb, "literature_outputs/traits_marked_for_lit_analysis_combined.tsv")

```


### Visualise lit space sizes


```{r}
lid_data<- read_tsv( "literature_outputs/traits_marked_for_lit_analysis.tsv")
lid_data<-lid_data %>% mutate(exposure_cat = ifelse(trait == 'Albumin', "Proteins", exposure_cat)) %>% 
  mutate(usable = ifelse(unique_triples >50 ,T, F)) %>% 
  mutate(exposure_cat = factor(exposure_cat, levels = rev(c("Antrophometric", "Diet and supplements", "Physical activity", "Reproductive", "Sleep", "Drugs", "Alcohol", "Smoking", "Proteins", "Lipids", "Metabolites", "Other biomarkers"))))

merged <- read_tsv("01_MR_related/mr_evidence_outputs/trait_manual_ivw_subtypes_merged.tsv")
keep_mr<- merged %>% filter_at(vars("ieu-a-1126":"TNBC ER-PR-HER-"), any_vars(. != 0) ) 

lid_data <- lid_data %>% filter(id %in% keep_mr$id.exposure)


p<- ggplot(lid_data, aes(y = unique_triples, x= exposure_cat, label = trait))+
  #geom_boxplot()+
  geom_violin()+
  geom_jitter(aes(colour = usable, alpha=0.3))+
  #ggrepel::geom_label_repel(size = 1)+
  scale_y_log10(breaks = c(0, 50, 100, 1000, 5000,10000, 50000))+
  coord_flip()+
  theme_bw()+
  labs(y = "Unique triples count", x= "Trait category")+
  theme(axis.text.x = element_text(angle=40, size=7, hjust = 1))

  
plotly::ggplotly(p)



# exckude stuff that is not in validated MR
# add repel labels? proteins - genenames?
# add joined groups ?
# lipids? 

```


