---
title: "MR on subtype outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(data.table)
library(vroom)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)

library(TwoSampleMR)
library(ggplot2)
library(cowplot)
library(wesanderson)
```

```{r message=F}
other_project_path <- "/Users/ny19205/OneDrive - University of Bristol/Documents - OneDrive/Mini-project2/"

bcac_lookup<-read_csv(paste0(other_project_path, "early-bmi-breast-cancer-mr//metadata/data_lookup_BCAC.csv")) 


# load functions
source(paste0(other_project_path, "early-bmi-breast-cancer-mr/functions.R"))
source(paste0(other_project_path, "early-bmi-breast-cancer-mr/functions_mvmr.R"))

```

```{r message=F}
# load all BC subtype data
bc_data<-list()
data_path_gwas <- paste0(other_project_path, "/01_Data/new_data/tidy_meta_analysed_data/")
for (i in bcac_lookup$full_data){
  print(paste0("Loading  ", i))
  bc_data[[i]]<- vroom(paste0(data_path_gwas, i)) 
}
```

```{r}

# load traits that have been validated in 'process_mr_results.Rmd'
traits_df <- read_tsv("mr_evidence_outputs/redone_MR_subsetoutput_ivw.tsv") 

traits<- traits_df%>%  pull(id.exposure) %>% unique()

length(traits) # 174

```


```{r message=F,  warnings=F}


for (trait in traits){
    print(paste0("====", trait, "===="))
  
    # load instruments
    trait1_exp <- extract_instruments(trait) #### NB not clumping??
  
    
    
    # MR against every BC subtype outcome
    trait_vs_subtypes<-tibble()
    for (bc_type in names(bc_data)){
        print(paste0(">> ", bc_type))
   
        outcome_mediator_trait1 <- bc_data[[bc_type]] %>%
                                filter(SNP %in% trait1_exp$SNP)
        # Harmonise 
        harmonised <- harmonise_data(exposure_dat = trait1_exp, 
                                 outcome_dat = outcome_mediator_trait1)
        # Perform MR
        res <- mr(harmonised, method_list=c('mr_ivw','mr_egger_regression','mr_weighted_median', 'mr_wald_ratio')) 
        
        if (dim(res)[1]!=0){
            # Tidy up results and save
            res_tidy<- res %>%
                        split_outcome() %>% 
                        split_exposure() %>% 
                        generate_odds_ratios() %>% 
                        arrange(method)
            
              # sensitivity
            if (dim(harmonised)[1]>1){
              res_sens <-
                full_join(mr_pleiotropy_test(harmonised),
                        mr_heterogeneity(harmonised, method_list=c("mr_egger_regression", "mr_ivw"))) %>% 
              split_outcome() %>%
              split_exposure() %>% 
              rename(egger_intercept_pval = pval,
                      egger_intercept_se = se)
            } else {
              # making dummy sens analysis table as a placeholder
              res_sens <- res %>% select(id.exposure, id.outcome, exposure, outcome, nsnp) %>% distinct() %>% mutate(method = "NO SENSITIVITY")
            }
        }  
            # join mr and sens in one table
            out <- full_join(res_tidy, res_sens)
            
            # add to main table with all outcomes
            trait_vs_subtypes<-bind_rows(trait_vs_subtypes, out)
        }

         # add useful cols
         trait_vs_subtypes <- trait_vs_subtypes  %>% select(-id.outcome) %>%
                              left_join(traits_df %>% select(id.exposure, exposure_name, exposure_cat)) %>% distinct()

         
         mr_res <- trait_vs_subtypes   %>% select(-starts_with('egger_intercept'), -starts_with('Q'))
         sens_res <- trait_vs_subtypes %>% select(id.exposure, exposure, outcome, method, nsnp,
                                                  starts_with('egger_intercept'), starts_with('Q'), ) %>% 
                                            filter(method != 'Weighted median')
         
         ind_res_dir <- paste0("mr_evidence_outputs/mr_subtypes/")
         write_tsv(mr_res, paste0(ind_res_dir, "MR_", trait,"-to-BCAC2020_subtypes.tsv" ))
         write_tsv(sens_res, paste0(ind_res_dir, "sens_", trait,"-to-BCAC2020_subtypes.tsv" ))
          
           
} 

```


```{r}
# join all files into one df

all.files <- list.files(path = paste0("mr_evidence_outputs/mr_subtypes/"), pattern = paste0("MR*"), full.names = T)
l <- lapply(all.files, read_tsv)
all_res<- bind_rows(l)

all_res<- all_res %>% 
  mutate(OR_CI = paste0(round(or,3), " [",round(or_lci95,3) ,":",round(or_uci95,3), "]")) %>% 
  mutate(effect_direction = ifelse(or_lci95 > 1 & or_uci95 >= 1, 'positive',
                            ifelse(or_lci95 < 1 & or_uci95 <= 1, 'negative', 'overlaps null'))) %>% 
    # fix issue with rounding negative effect to 1 
    mutate(OR_CI = ifelse(effect_direction == 'negative' & OR_CI == '1 [1:1]', "0.99 [0.99:0.99]", OR_CI))


write_tsv(all_res, paste0("mr_evidence_outputs/mr_subtypes/all_traits_MR_vs_BCAC2020.tsv"))
```





```{r message=F}
## Making plots  ---- old set-up does not work right now

for (trait in traits){
  
  all.files <- list.files(path = paste0(results_path, "new_bcac/"), pattern = paste0("MR_", trait,"-to-*"), full.names = T)
  l <- lapply(all.files, read_tsv)
  
  dat<-
    bind_rows(l) %>% 
    filter(method %in% c("Inverse variance weighted", "Wald ratio")) %>% 
    select( -method) %>% 
    mutate(mr="Univariable MR") %>% 
    mutate(outcome = case_when(outcome == 'Luminal B-HER2 negative' ~ 'Luminal B1: ER+PR+HER-',
                               outcome == 'Luminal B'        ~ 'Luminal B2: ER+PR+HER+',
                               outcome == 'Luminal A'        ~ 'Luminal A: ER+PR+HER-',
                               outcome == 'HER2 enriched'    ~ 'HER2-enriched: ER-PR-HER+',
                               outcome == 'TNBC Basal-like'  ~ 'Basal-like TNBC: ER-PR-HER-',
                               outcome == 'CIMBA_BRCA1_BCAC_TN' ~ 'BRCA1_CIMBA TNBC: ER-PR-HER-',
                               TRUE ~ outcome)) %>% 
    mutate(OR_CI =  paste0(round(or,2), " [",round(or_lci95,2) ,":",round(or_uci95,2), "]"))
  
  #dat %>% kable_it()
  
  pal <- wes_palette("Zissou1")[c(1,5)]
  dat$mr <- forcats::fct_rev(dat$mr) 
  p<-ggplot(dat, aes(y=exposure, x=or, label=outcome, colour=exposure,  shape=exposure)) +
    geom_errorbarh(aes(xmin=or_lci95, xmax=or_uci95), height=.3) +
    geom_point(size=3)+
    geom_text(aes(label=OR_CI),hjust=-0.1, vjust=-0.6, size =3, color = 'darkgrey')+
    scale_color_manual(values=pal)+
    scale_shape_manual(values = c(16,20)) +
    geom_vline(xintercept=1, linetype='longdash') +
    theme_minimal_hgrid(9, rel_small = 1) +
    facet_wrap(~outcome, ncol=1)+
    labs(color = "",y = "", x = "Odds ratio",
         title= paste0("        IVW MR results") )+
    theme(legend.position = "none", panel.grid.major.x = element_line())
  
  
  
  ggsave(paste0("/Users/ny19205/Documents/Projects_IEU/epigraphdb_breast_cancer/R/external_figures/new_bcac_", trait, ".png"),
         plot=p, scale=1.2, 
         width=15, height=10,
         units=c("cm"), dpi=300, limitsize=F)
  
}
```





