---
title: "Explore traits by category"
output: html_notebook
---


```{r}
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggplot2)
library(wesanderson)
library(cowplot)

library(TwoSampleMR)
```

```{r}
if (!exists("ao")) {
  ao <- available_outcomes()
  ao<-ao %>% filter(!grepl('ukb-e-', id)) %>% 
      filter(sex!= 'Males') %>% 
      filter(population == 'European')
}
```

```{r}
activity_ids <- ao %>% 
        filter(grepl('activity', trait),
        grepl("Types of physical activity|Time spent doing|activity 10+ minutes|Duration of", trait)) %>%  
        select(id, trait, sex, note, year, consortium)  %>% 
        mutate(category = 'activity')

acitivity_summary <- ao %>% 
    filter(grepl('activity', trait),
    grepl("Types of physical activity|Time spent doing|activity 10+ minutes|Duration of", trait)) %>% 
    filter(consortium =='Neale Lab') %>% 
    mutate(category = ifelse(grepl("Types", trait), 'Binary', category)) %>% 
    select(id, trait, category, sample_size,  ncase, ncontrol) %>% 
    mutate(percent_cases = round(ncase/sample_size*100, 1)) %>% 
    arrange(-percent_cases)

```


```{r}

reproductive_ids <- 
  ao %>% filter(grepl('menopause|menarche|live birth|parous|contraceptive pill|replacement therapy', trait) )%>% 
        select(id, trait, sex, note, year, consortium)  %>% 
        mutate(category = 'reproductive traits')
```


```{r}

antrophometric_ids <- 
  ao %>% filter(grepl('waist|hip c|hip rat|obesity|trunk fat|mass|weight|bmi|body size|height|impedance|fat percentage|body fat|Childhood obesity|Obesity class|size at age 10', trait) ) %>% 
          filter(!grepl("arm|leg|first child|depression", trait, ignore.case = T)) %>% 
          #bind_rows(ao %>% filter(grepl('circumference', trait, ignore.case = T), population == 'European', sex == 'Females')) %>% 
          #bind_rows(ao %>% filter(id %in% c("ieu-b-40", "ukb-b-19953", 	"ukb-b-9405", "ukb-b-15590",
          #                "ieu-a-974","ukb-b-16881","ukb-b-10787","ieu-a-97",
          #                "ieu-a-1032", 	"ieu-a-1035","ieu-a-1038","ieu-a-75", 	
          #                "ieu-a-81", "ieu-a-109", "ieu-a-111", 	"ieu-a-87",
          #                "ukb-b-13378","ieu-a-29","ieu-a-27"))) %>% 
        select(id, trait, sex, note, year,author, consortium) %>%
        mutate(trait = case_when(note == 'Adjusted for BMI' ~ paste0(trait, " AdjBMI"),
                        TRUE ~ trait)) %>% 
        arrange(trait) %>% 
       mutate(category = 'antrophometric traits')

```

```{r}
all_traits<- bind_rows(activity_ids,
                       reproductive_ids,
                       antrophometric_ids)
write_tsv(all_traits %>% select(id), "../query_results/gwas_rf_list.txt")

# next  extract MR-eve data from the graph in the notebook 1
```



```{r}
# load mr data and join with metadata
mr_results<- read_tsv("../query_results/gwas_rf_bc_all_mr.tsv") %>% 
            left_join(., all_traits %>% select(id, trait,category), by = c('exposure.id' = 'id', 'exposure.trait' = 'trait' ))

rm(res)
res <- mr_results %>% 
  # tidy up outcome info
mutate(outcome = case_when(
        outcome.id %in% c('ieu-a-1127','ieu-a-1132', 'ieu-a-1133', 'ieu-a-1134', 'ieu-a-1167', 'ieu-a-1164', 'ieu-a-1161') ~ 'ER+ postmeno',
        outcome.id %in% c('ieu-a-1128','ieu-a-1135', 'ieu-a-1136', 'ieu-a-1137', 'ieu-a-1166', 'ieu-a-1163', 'ieu-a-1160') ~ 'ER- premeno',
        outcome.id %in% c('ieu-a-1126','ieu-a-1129', 'ieu-a-1130', 'ieu-a-1131', 'ieu-a-1168', 'ieu-a-1165', 'ieu-a-1162', 'ebi-a-GCST004988', 'ebi-a-GCST007236') ~ 'Breast cancer (all)',
        grepl('ukb', outcome.id) ~ 'ER+ postmeno UKB')) %>% 
 mutate(chip = case_when(
        outcome.id %in% c('ieu-a-1126','ieu-a-1127', 'ieu-a-1128', 'ebi-a-GCST004988') ~ 'Meta',
        outcome.id %in% c('ieu-a-1129', 'ieu-a-1132','ieu-a-1135') ~                     'OncArray',
        outcome.id %in% c('ieu-a-1130', 'ieu-a-1133','ieu-a-1136') ~                     'iCOG2017',
        outcome.id %in% c('ieu-a-1161', 'ieu-a-1160','ieu-a-1162', 'ebi-a-GCST007236') ~ 'iCOG2015',
        outcome.id %in% c('ieu-a-1131', 'ieu-a-1134','ieu-a-1137') ~                     'GWASold1',
        outcome.id %in% c('ieu-a-1166', 'ieu-a-1167','ieu-a-1168') ~                     'GWASold2',
        outcome.id %in% c('ieu-a-1163', 'ieu-a-1164','ieu-a-1165') ~                     'Survival_',
        grepl('ukb', outcome.id) ~                                                       'UKBB')) %>% 
    # subset 
  filter(exposure.sex != 'Males') %>% 
  filter(outcome.id != 'ebi-a-GCST007236') %>% 
  # create outcome label
  mutate(outcome.details =  paste0(outcome.id, " (",format(outcome.sample_size, big.mark = ","))) %>% 
  separate(outcome.details, into=c('outcome.details', 'tmp'), sep=",") %>% 
  mutate(outcome.details = gsub("ieu-a-|ukb-a-|ukb-b-|ukb-d-|ebi-a-GCST00", '', outcome.details),
         outcome.details = paste0(chip, ": ",outcome.details, "K)")) %>% 
  # create tidy exposure sample size
  mutate(exposure.ss = format(exposure.sample_size, big.mark = ",")) %>% 
  separate(exposure.ss, into=c('exposure.ss', 'tmp'), sep=",") %>% 
  mutate(exposure.ss_label = paste0(" [",exposure.ss,"K]"))
  

res<- res %>% 
  #mutate(outcome.details = factor(outcome.details, levels= c( 
  #                  sort(unique(dat$outcome.details)[grepl('Meta', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('OncArray', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('iCOG2017', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('iCOG2015', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('GWASold1', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('GWASold2', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('Survival_', unique(dat$outcome.details))]),
  #                  sort(unique(dat$outcome.details)[grepl('UKBB', unique(dat$outcome.details))])  ))) %>% 
  # convert MR results to OR
  mutate(loci = mr.b - 1.96 * mr.se, 
         upci = mr.b + 1.96 * mr.se,
         or = exp(mr.b), 
         or_loci = exp(loci), 
         or_upci = exp(upci),
         OR_CI = paste0(round(or,2), " [",round(or_loci,2) ,":",round(or_upci,2), "]")) %>% 
  mutate(effect_direction = ifelse(or_loci > 1 & or_upci > 1, 'positive',
                            ifelse(or_loci < 1 & or_upci < 1, 'negative', 'overlaps null'))) %>% 
  mutate(mr.b = round(mr.b, 3)) %>% 
  mutate(`MR method and score` = paste0(mr.method," / ", mr.moescore)) %>% 
  mutate(exposure = case_when(
          exposure.sex == 'Females' ~ paste0(exposure.trait, " (F) ", coalesce(consortium, author),"/" , year, exposure.ss_label),
                               TRUE ~ paste0(exposure.trait, " (M/F) ", coalesce(consortium, author),"/" , year, exposure.ss_label)))%>% 
    # add note
  mutate(exposure = case_when(grepl('Adjusted for BMI', exposure.note) ~ paste0(exposure, " AdjBMI"),
                        TRUE ~ exposure)) 
        
```


```{r}
 
makeforest_plot <- function(res_sub, my_title){
  
  pal<-c(wes_palette("Zissou1"))
  p<-ggplot(res_sub, 
         aes(y=reorder(exposure, -or), x=or, label=outcome.details, colour=effect_direction)) +
    geom_errorbarh(aes(xmin=or_loci, xmax=or_upci), height=.3) +
    geom_point(size=2)+
    geom_text(aes(label=OR_CI),hjust=-0.1, vjust=-0.6, size =3, color = 'darkgrey')+
    theme_light()+
    scale_color_manual(values=pal[c(1,3,5)])+
    scale_y_discrete(position = "left")+
    geom_vline(xintercept=1, linetype='longdash') +
    theme(strip.text = element_text(face = 'bold'))+
    facet_grid(~outcome.details, scales = 'free') +
    labs(color = "",y = "", x = "Odds ratio", subtitle="",
         title=paste0("         ", my_title))+
    theme(legend.position = "none")
  return(p)
}

```



## Antrophometric traits

```{r fig.width = 10,echo=F}
res_sub<- res %>% 
      filter(category == 'antrophometric traits') %>% 
      mutate(exposure.trait = gsub("Difference in height between ", "Height diff: ", exposure.trait)) %>% 
      mutate(exposure.trait = gsub("Comparative ", "", exposure.trait)) %>% 
      filter(!(grepl("hip|waist",exposure.trait, ignore.case=T) & grepl("2013", exposure.trait)))

```

```{r}
#meta
#meta
res_sub1 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1126', 'ieu-a-1127','ieu-a-1128'))
antr_p1<-makeforest_plot(res_sub1, "BCAC meta analysis")

# oncoarray
res_sub2 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1129', 'ieu-a-1132','ieu-a-1135'))
antr_p2<-makeforest_plot(res_sub2, "BCAC oncoarray")

#iCOGS
res_sub3 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1130', 'ieu-a-1133','ieu-a-1136'))
antr_p3<-makeforest_plot(res_sub3, "BCAC iCOGS")

#UKB
res_sub4 <- res_sub %>% filter(outcome.id %in% c('ukb-a-55', 'ukb-a-519'))
antr_p4<-makeforest_plot(res_sub4, "UK biobank NL")
```


```{r fig.width = 10, echo=F}
antr_p1
```


```{r fig.width = 10,echo=F}
antr_p2
```


```{r fig.width = 10,echo=F}
antr_p3
```

```{r fig.width = 8,echo=F}
antr_p4
```



## Activity traits
```{r}

res_sub<- res %>% 
      filter(category == 'activity') %>% 
      mutate(exposure.trait = str_replace(exposure.trait, 
                                    "Types of physical activity in last 4 weeks", "Physical activity")) %>% 
      mutate(exposure.trait = gsub("\\(eg.*)", "", exposure.trait)) %>% 
      mutate(exposure.trait = gsub("\\(not.*)", "", exposure.trait))


#meta
res_sub1 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1126', 'ieu-a-1127','ieu-a-1128'))
act_p1<-makeforest_plot(res_sub1, "BCAC meta analysis")

# oncoarray
res_sub2 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1129', 'ieu-a-1132','ieu-a-1135'))
act_p2<-makeforest_plot(res_sub2, "BCAC oncoarray")

#iCOGS
res_sub3 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1130', 'ieu-a-1133','ieu-a-1136'))
act_p3<-makeforest_plot(res_sub3, "BCAC iCOGS")

#UKB
res_sub4 <- res_sub %>% filter(outcome.id %in% c('ukb-a-55', 'ukb-a-519'))
act_p4<-makeforest_plot(res_sub4, "UK biobank NL")
```

```{r fig.width = 10, fig.height=4, echo=F}
act_p1
```
```{r}

acitivity_summary<- acitivity_summary %>% 
  mutate(trait = str_replace(trait, 
                           "Types of physical activity in last 4 weeks", "Physical activity")) %>% 
  mutate(trait = gsub("\\(eg.*)", "", trait)) %>% 
  mutate(trait = gsub("\\(not.*)", "", trait))

set_flextable_defaults(big.mark = " ", 
  font.size = 10, theme_fun = theme_vanilla,
  padding.bottom = 6, 
  padding.top = 6,
  padding.left = 6,
  padding.right = 6,
  background.color = "#EFEFEF")

ft<-flextable(acitivity_summary)
ft<-width(ft, j = 2, width=4)
ft<-width(ft, j = 1, width=1.5)
ft<-width(ft, j = 5, width=1.5)

ft
```


```{r fig.width = 10,fig.height=4, echo=F}
act_p2
```


```{r fig.width = 10,fig.height=4, echo=F}
act_p3
```

```{r fig.width = 8,fig.height=3.5, echo=F}
act_p4
```



## Reproductive traits

```{r fig.width = 10,echo=F}
res_sub<- res %>% 
      filter(category == 'reproductive traits') %>% 
      filter(exposure.trait != "Medication for cholesterol  blood pressure  diabetes  or take exogenous hormones: Hormone replacement therapy") %>% 
      mutate(exposure.trait = paste(exposure.trait, consortium, year)) 

```

```{r}
#meta
#meta
res_sub1 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1126', 'ieu-a-1127','ieu-a-1128'))
repr_p1<-makeforest_plot(res_sub1, "BCAC meta analysis")

# oncoarray
res_sub2 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1129', 'ieu-a-1132','ieu-a-1135'))
repr_p2<-makeforest_plot(res_sub2, "BCAC oncoarray")

#iCOGS
res_sub3 <- res_sub %>% filter(outcome.id %in% c('ieu-a-1130', 'ieu-a-1133','ieu-a-1136'))
repr_p3<-makeforest_plot(res_sub3, "BCAC iCOGS")

#UKB
res_sub4 <- res_sub %>% filter(outcome.id %in% c('ukb-a-55', 'ukb-a-519'))
repr_p4<-makeforest_plot(res_sub4, "UK biobank NL")
```


```{r fig.width = 10, fig.height = 5, echo=F}
repr_p1
```


```{r fig.width = 10, fig.height = 5,echo=F}
repr_p2
```


```{r fig.width = 10, fig.height = 5, echo=F}
repr_p3
```

```{r fig.width = 8,fig.height = 5, echo=F}
repr_p4
```


